/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cmy_media_AVService */

#ifndef _Included_com_cmy_media_AVService
#define _Included_com_cmy_media_AVService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cmy_media_AVService
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_cmy_media_AVService_init
  (JNIEnv *, jobject);

/*
 * Class:     com_cmy_media_AVService
 * Method:    startServer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_cmy_media_AVService_startServer
  (JNIEnv *, jobject);

/*
 * Class:     com_cmy_media_AVService
 * Method:    stopServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cmy_media_AVService_stopServer
  (JNIEnv *, jobject);

/*
 * Class:     com_cmy_media_AVService
 * Method:    sendVideoToRemote
 * Signature: (Ljava/lang/String;[BI)V
 */
JNIEXPORT void JNICALL Java_com_cmy_media_AVService_sendVideoToRemote
  (JNIEnv *, jobject, jstring, jbyteArray, jint);

/*
 * Class:     com_cmy_media_AVService
 * Method:    sendAudioToRemote
 * Signature: (Ljava/lang/String;[SI)V
 */
JNIEXPORT void JNICALL Java_com_cmy_media_AVService_sendAudioToRemote
  (JNIEnv *, jobject, jstring, jshortArray, jint);

#ifdef __cplusplus
}
#endif
#endif
