/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdlib.h> // for NULL
#include <assert.h>
#include <echo_control_mobile.h>
#include "com_wrtcmy_webrtc_aecm_AECM.h"
/* Header for class com_wrtcmy_webrtc_aecm_AECM */

/*
 * Class:     com_wrtcmy_webrtc_aecm_AECM
 * Method:    nativeCreateAecmInstance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_aecm_AECM_nativeCreateAecmInstance
  (JNIEnv *env,jclass jclazz) {
		void *aecmInstHandler = NULL;
		if (WebRtcAecm_Create(&aecmInstHandler) == -1)
			return -1;
		else
			return ((int) aecmInstHandler); //returns the pointer which points to created AECM instance to JAVA layer.
	}


/*
 * Class:     com_wrtcmy_webrtc_aecm_AECM
 * Method:    nativeFreeAecmInstance
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_aecm_AECM_nativeFreeAecmInstance
  (JNIEnv *env, jclass jclazz, jint aecmHandler) {
	void *aecmInst = (void *) aecmHandler;
	if (aecmInst == NULL)
		return -1;
	int ret = WebRtcAecm_Free(aecmInst);
	aecmInst = NULL;
	return ret;
}


/*
 * Class:     com_wrtcmy_webrtc_aecm_AECM
 * Method:    nativeInitializeAecmInstance
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_aecm_AECM_nativeInitializeAecmInstance
  (JNIEnv *env, jclass jclazz, jint aecmHandler, jint sampFreq) {
	void *aecmInst = (void *) aecmHandler;
	if (aecmInst == NULL)
		return -1;
	return WebRtcAecm_Init(aecmInst, sampFreq);
}

/*
 * Class:     com_wrtcmy_webrtc_aecm_AECM
 * Method:    nativeBufferFarend
 * Signature: (I[SI)I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_aecm_AECM_nativeBufferFarend
  (JNIEnv *env, jclass jclazz, jint aecmHandler, jshortArray farend,
			jint nrOfSamples) {
		void *aecmInst = (void *) aecmHandler;
		if (aecmInst == NULL)
			return -1;

		int ret = -1;
		if (farend != NULL) {
			short *arrFarend = (*env)->GetShortArrayElements(env, farend, NULL);
			ret = WebRtcAecm_BufferFarend(aecmInst, arrFarend, nrOfSamples);

			//TODO(billhoo) should use JNI_ABORT instead of 0 in 4th param.
			//I think there is no need to copy this array back to Java layer.
			(*env)->ReleaseShortArrayElements(env, farend, arrFarend, 0);
		}
		return ret;
	}
/*
 * Class:     com_wrtcmy_webrtc_aecm_AECM
 * Method:    nativeAecmProcess
 * Signature: (I[S[S[SSS)I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_aecm_AECM_nativeAecmProcess
  (JNIEnv *env, jclass jclazz, jint aecmHandler,
			const jshortArray nearendNoisy, const jshortArray nearendClean,
			jshortArray out, jshort nrOfSamples, jshort msInSndCardBuf) {

		int16_t *arrNearendNoisy = NULL;
		int16_t *arrNearendClean = NULL;
		int16_t *arrOut = NULL;

		void *aecmInst = (void *) aecmHandler;
		if (aecmInst == NULL)
			return -1;

		int ret = -1;

		//nearendNoisy and out must not be NULL, otherwise process can not be run, return -1 for error.
		if (nearendNoisy == NULL || out == NULL)
			return ret;

		//get data from java side.
		arrNearendNoisy = (*env)->GetShortArrayElements(env, nearendNoisy, NULL);
		arrOut = (*env)->GetShortArrayElements(env, out, NULL);

		if (nearendClean != NULL)
			arrNearendClean = (*env)->GetShortArrayElements(env, nearendClean,
					NULL);

		ret = WebRtcAecm_Process(aecmInst, arrNearendNoisy, arrNearendClean, arrOut,
				nrOfSamples, msInSndCardBuf);

		//release and send the changes back to java side.
		(*env)->ReleaseShortArrayElements(env, nearendNoisy, arrNearendNoisy, 0);
		(*env)->ReleaseShortArrayElements(env, out, arrOut, 0);

		if (nearendClean != NULL)
			(*env)->ReleaseShortArrayElements(env, nearendClean, arrNearendClean,
					0);

		return ret;
	}

/*
 * Class:     com_wrtcmy_webrtc_aecm_AECM
 * Method:    nativeSetConfig
 * Signature: (ILcom/wrtcmy/webrtc/aecm/AECM/AecmConfig;)I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_aecm_AECM_nativeSetConfig
  (JNIEnv *env, jclass jclazz, jint aecmHandler, jobject aecmConfig) {

	void * aecmInst = (void *) aecmHandler;
	if (aecmInst == NULL)
		return -1;

	//get reference of AecmConfig class  from java side.
	jclass JavaAecmConfig = (*env)->GetObjectClass(env, aecmConfig);

	//assertion that class not be NULL
	//TODO(billhoo) should use Exception handler to handle this situation instead of assertion.
	assert(JavaAecmConfig != NULL);

	//get configuration field IDs from java side.
	jfieldID mAecmModeID = (*env)->GetFieldID(env, JavaAecmConfig, "mAecmMode",
			"S");
	jfieldID mCngModeID = (*env)->GetFieldID(env, JavaAecmConfig, "mCngMode",
			"S");

	//if any ID is NULL, return -1 for error.
	if (mAecmModeID == NULL || mCngModeID == NULL){
	    LOGD("$$$$$$$$$$nativeSetConfig->(mAecmModeID == NULL || mCngModeID == NULL)");
		return -1;
	}
	//get values of fields
	short echoMode = (*env)->GetShortField(env, aecmConfig, mAecmModeID);
	short cngMode = (*env)->GetShortField(env, aecmConfig, mCngModeID);

	//set new configuration to AECM instance.
	AecmConfig config;
	config.echoMode = echoMode;
	config.cngMode = cngMode;

    LOGD("$$$$$$$$$$WebRtcAecm_set_config");
	return WebRtcAecm_set_config(aecmInst, config);
}

