/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wrtcmy_webrtc_aecm_AECM_AggressiveMode */

#ifndef _Included_com_wrtcmy_webrtc_aecm_AECM_AggressiveMode
#define _Included_com_wrtcmy_webrtc_aecm_AECM_AggressiveMode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
