/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wrtcmy_webrtc_aecm_AECM */


#include <android/log.h>

#define TAG    "$$$$webrtc_aecm$$$$" // 这个是自定义的LOG的标识
#define LOGI(format, ...)  __android_log_print(ANDROID_LOG_INFO,  TAG, format, ##__VA_ARGS__)
#define LOGD(format, ...)  __android_log_print(ANDROID_LOG_DEBUG,  TAG, format, ##__VA_ARGS__)


#ifndef _Included_com_wrtcmy_webrtc_aecm_AECM
#define _Included_com_wrtcmy_webrtc_aecm_AECM
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wrtcmy_webrtc_aecm_AECM_AECM_UNABLE
#define com_wrtcmy_webrtc_aecm_AECM_AECM_UNABLE 0L
#undef com_wrtcmy_webrtc_aecm_AECM_AECM_ENABLE
#define com_wrtcmy_webrtc_aecm_AECM_AECM_ENABLE 1L
/*
 * Class:     com_wrtcmy_webrtc_aecm_AECM
 * Method:    nativeCreateAecmInstance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_aecm_AECM_nativeCreateAecmInstance
  (JNIEnv *, jclass);

/*
 * Class:     com_wrtcmy_webrtc_aecm_AECM
 * Method:    nativeFreeAecmInstance
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_aecm_AECM_nativeFreeAecmInstance
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_wrtcmy_webrtc_aecm_AECM
 * Method:    nativeInitializeAecmInstance
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_aecm_AECM_nativeInitializeAecmInstance
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_wrtcmy_webrtc_aecm_AECM
 * Method:    nativeBufferFarend
 * Signature: (I[SI)I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_aecm_AECM_nativeBufferFarend
  (JNIEnv *, jclass, jint, jshortArray, jint);

/*
 * Class:     com_wrtcmy_webrtc_aecm_AECM
 * Method:    nativeAecmProcess
 * Signature: (I[S[S[SSS)I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_aecm_AECM_nativeAecmProcess
  (JNIEnv *, jclass, jint, jshortArray, jshortArray, jshortArray, jshort, jshort);

/*
 * Class:     com_wrtcmy_webrtc_aecm_AECM
 * Method:    nativeSetConfig
 * Signature: (ILcom/wrtcmy/webrtc/aecm/AECM/AecmConfig;)I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_aecm_AECM_nativeSetConfig
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
