/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wrtcmy_webrtc_aecm_AECM_SamplingFrequency */

#ifndef _Included_com_wrtcmy_webrtc_aecm_AECM_SamplingFrequency
#define _Included_com_wrtcmy_webrtc_aecm_AECM_SamplingFrequency
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
