/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wrtcmy_webrtc_ns_NS */


#include <android/log.h>

#define TAG    "$$$$webrtc_ns$$$$" // 这个是自定义的LOG的标识
#define LOGI(format, ...)  __android_log_print(ANDROID_LOG_INFO,  TAG, format, ##__VA_ARGS__)
#define LOGD(format, ...)  __android_log_print(ANDROID_LOG_DEBUG,  TAG, format, ##__VA_ARGS__)


#ifndef _Included_com_wrtcmy_webrtc_ns_NS
#define _Included_com_wrtcmy_webrtc_ns_NS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wrtcmy_webrtc_ns_NS
 * Method:    nsCreate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_ns_NS_nsCreate
  (JNIEnv *, jobject);

/*
 * Class:     com_wrtcmy_webrtc_ns_NS
 * Method:    nsInit
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_ns_NS_nsInit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wrtcmy_webrtc_ns_NS
 * Method:    nsSetPolicy
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_ns_NS_nsSetPolicy
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wrtcmy_webrtc_ns_NS
 * Method:    nsProcess
 * Signature: (I[S[S[S[S)I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_ns_NS_nsProcess
  (JNIEnv *, jobject, jint, jshortArray, jshortArray, jshortArray, jshortArray);

/*
 * Class:     com_wrtcmy_webrtc_ns_NS
 * Method:    nsFree
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_ns_NS_nsFree
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wrtcmy_webrtc_ns_NS
 * Method:    nsxCreate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_ns_NS_nsxCreate
  (JNIEnv *, jobject);

/*
 * Class:     com_wrtcmy_webrtc_ns_NS
 * Method:    nsxInit
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_ns_NS_nsxInit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wrtcmy_webrtc_ns_NS
 * Method:    nsxSetPolicy
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_ns_NS_nsxSetPolicy
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wrtcmy_webrtc_ns_NS
 * Method:    nsxProcess
 * Signature: (I[S[S[S[S)I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_ns_NS_nsxProcess
  (JNIEnv *, jobject, jint, jshortArray, jshortArray, jshortArray, jshortArray);

/*
 * Class:     com_wrtcmy_webrtc_ns_NS
 * Method:    nsxFree
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wrtcmy_webrtc_ns_NS_nsxFree
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
